### ISSUE TITLE
running dm3270 on Ubuntu 

### ISSUE THREAD

**Issue by vmdave9** [dmolony/dm3270#10]

**Comment by vmdave9** [comment]
system:
  4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
java version:
  ./java --version
  openjdk 11.0.2 2019-01-15
  OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
  OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
startup script:
#!/bin/bash
/home/dave/Downloads/jdk-11.0.2/bin/java    \
--module-path /home/dave/Downloads/javafx-sdk-11.0.2/lib         \
--add-modules=javafx.controls                     \
-Dfile.encoding=UTF-8                             \
-jar /home/dave/Downloads/dm3270.jar

However, when  I run the script, and click on the connect button I get this error:
./davedm3270.sh
setting: IBM-3278-2-E
model: 4
setting: IBM-3278-4-E
Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class com.bytezone.dm3270.display.FontDetails (in unnamed module @0xc3c194d) cannot access class com.sun.javafx.tk.Toolkit (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.tk to unnamed module @0xc3c194d
	at com.bytezone.dm3270.display.FontDetails.<init>(FontDetails.java:26)
	at com.bytezone.dm3270.display.FontManagerType1.setFont(FontManagerType1.java:200)
	at com.bytezone.dm3270.display.FontManagerType1.<init>(FontManagerType1.java:43)
	at com.bytezone.dm3270.display.FontManager.getInstance(FontManager.java:12)

 I suspect a path is  not set up the way it shoud be here. Thanks.
DJ
