### ISSUE TITLE
errored when connecting to my machine

### ISSUE THREAD

**Issue by johnbx** [dmolony/dm3270#2]
java dump is..running in linux ubuntu 14.04lts

setting: IBM-3278-2-E
model: 3
setting: IBM-3278-3-E
Exception in thread "Thread-6" java.security.InvalidParameterException: Unknown telnet command type: FB 03

        at com.bytezone.dm3270.telnet.TelnetCommand.<init>(TelnetCommand.java:90)
        at com.bytezone.dm3270.streams.TelnetListener.processTelnetCommand(TelnetListener.java:169)
        at com.bytezone.dm3270.telnet.TelnetProcessor.listen(TelnetProcessor.java:120)
        at com.bytezone.dm3270.streams.TelnetListener.listen(TelnetListener.java:86)
        at com.bytezone.dm3270.streams.TerminalServer.run(TerminalServer.java:73)
        at java.lang.Thread.run(Thread.java:745)

Looks like a great program...

**Comment by dmolony** [comment]
Are you able to run it as a MITM? Then you could send me the commands. Alternatively is it possible for me to connect to the site?

**Comment by dmolony** [comment]
No reply.
