### ISSUE TITLE
Unknown telnet command type

### ISSUE THREAD

**Issue by andreig09** [dmolony/dm3270#4]
Hi,

I'm having the following error:

C:\Users\andrei\Downloads>java -jar dm3270.jar
setting: IBM-3278-2-E
model: 2
setting: IBM-3278-2-E
C:\Users\andrei\dm3270\files not valid
Exception in thread "Thread-6" java.security.InvalidParameterException: Unknown telnet command type: FD 27

        at com.bytezone.dm3270.telnet.TelnetCommand.<init>(TelnetCommand.java:90)
        at com.bytezone.dm3270.streams.TelnetListener.processTelnetCommand(TelnetListener.java:169)
        at com.bytezone.dm3270.telnet.TelnetProcessor.listen(TelnetProcessor.java:120)
        at com.bytezone.dm3270.streams.TelnetListener.listen(TelnetListener.java:86)
        at com.bytezone.dm3270.streams.TerminalServer.run(TerminalServer.java:73)
        at java.lang.Thread.run(Thread.java:745)

Any ideas or suggestions?

Thanks in advance

**Comment by dmolony** [comment]
Hi andreig09

Did you receive my direct reply?

**Comment by andreig09** [comment]
Hi @dmolony,

I haven't received your direct reply, sorry.

I just realized that I was trying the emulator with a 5250 environment instead of a 3270. Maybe the error is related to this?

**Comment by dmolony** [comment]
I believe the problem has been corrected, but I am unable to recreate the problem. The fix is in the latest source, and will be included in the next release.

**Comment by andreig09** [comment]
Yes, i think that i was doing something wrong, because i didn't have the
error again.

Thank you for your time, this tool is awesome!

2018-03-29 21:17 GMT-03:00 Denis Molony <notifications@github.com>:
