### ISSUE TITLE
Not able to find package in source 

### ISSUE THREAD

**Issue by stagging18** [dmolony/dm3270#7]
Hi dmolony,

I am not able to find com.bytezone.dm3270.database package in yours src.
Can you please help me find out these package so i can compile the code and make it executable.

Regards,
Rajesh

**Comment by stagging18** [comment]
I have also tried to execute the jar file and found the below issue

java -jar dm3270.jar

setting: IBM-3278-2-E
model: 2
setting: IBM-3278-2-E
C:\Users\rajesh\dm3270\files not valid
Does Terminal type  : true
Does Terminal type  : true
Exception in thread "Thread-6" java.security.InvalidParameterException: Unknown telnet command type: FD 20

        at com.bytezone.dm3270.telnet.TelnetCommand.<init>(TelnetCommand.java:90)
        at com.bytezone.dm3270.streams.TelnetListener.processTelnetCommand(TelnetListener.java:169)
        at com.bytezone.dm3270.telnet.TelnetProcessor.listen(TelnetProcessor.java:120)
        at com.bytezone.dm3270.streams.TelnetListener.listen(TelnetListener.java:86)
        at com.bytezone.dm3270.streams.TerminalServer.run(TerminalServer.java:73)
        at java.lang.Thread.run(Unknown Source)

**Comment by stagging18** [comment]
Is there anyone who can help me to resolve this issue.

I am not able to connect to my server with this tool and getting the above mentioned error.

**Comment by dmolony** [comment]
The error has been fixed, but you will need to recompile the source. The database package is a separate project.

**Comment by stagging18** [comment]
Hi dmolony,

Is there any latest compiled jar available in
https://github.com/dmolony/dm3270/releases

with this fixes or do we need to recompile it manually.

**Comment by stagging18** [comment]
Hi Denish,

I have recompiled the source and tried to execute your code and found the below exception.

C:\Users\cavisson-267\Desktop>java -jar dm3270.jar
setting: IBM-3278-2-E
model: 2
setting: IBM-3278-2-E
java.sql.SQLException: path to 'C:\Users\cavisson-267\dm3270\databases\10.10.70.6.db': 'C:\Users\cavisson-267\dm3270\databases' does no
 exist
        at org.sqlite.Conn.<init>(Conn.java:41)
        at org.sqlite.JDBC.connect(JDBC.java:53)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at com.bytezone.dm3270.database.DatabaseThread.<init>(DatabaseThread.java:53)
        at com.bytezone.dm3270.display.FieldManager.<init>(FieldManager.java:53)
        at com.bytezone.dm3270.display.Screen.<init>(Screen.java:117)
        at com.bytezone.dm3270.application.Console.createScreen(Console.java:327)
        at com.bytezone.dm3270.application.Console.startSelectedFunction(Console.java:147)
        at com.bytezone.dm3270.application.Console.lambda$start$1(Console.java:87)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8413)
        at javafx.scene.control.Button.fire(Button.java:185)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:417)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-5" java.lang.NullPointerException
        at com.bytezone.dm3270.database.DatabaseThread.run(DatabaseThread.java:70)
10.10.70.6
Does Terminal type  : true
Does Terminal type  : true
Unknown telnet command type: FD 20
Unknown telnet command type: FC 20
Unknown telnet command type: FC 20
Unknown telnet command type: FD 23
Unknown telnet command type: FC 23
Unknown telnet command type: FC 23
Unknown telnet command type: FD 27
Unknown telnet command type: FC 27
Unknown telnet command type: FC 27
Terminal            : IBM-3278-2-E
Unknown telnet command type: FB 03
Exception in thread "Thread-7" java.lang.IllegalArgumentException: Unknown telnet command: 00 03

        at com.bytezone.dm3270.telnet.TelnetCommand.<init>(TelnetCommand.java:77)
        at com.bytezone.dm3270.telnet.TelnetCommand.<init>(TelnetCommand.java:42)
        at com.bytezone.dm3270.telnet.TelnetCommand.process(TelnetCommand.java:180)
        at com.bytezone.dm3270.streams.TelnetListener.processMessage(TelnetListener.java:218)
        at com.bytezone.dm3270.streams.TelnetListener.addDataRecord(TelnetListener.java:210)
        at com.bytezone.dm3270.streams.TelnetListener.processTelnetCommand(TelnetListener.java:170)
        at com.bytezone.dm3270.telnet.TelnetProcessor.listen(TelnetProcessor.java:120)
        at com.bytezone.dm3270.streams.TelnetListener.listen(TelnetListener.java:86)
        at com.bytezone.dm3270.streams.TerminalServer.run(TerminalServer.java:73)
        at java.lang.Thread.run(Unknown Source)


can you please help us to resolve this or am i doing something wrong.

Regards,
Rajesh

**Comment by dmolony** [comment]
I haven't looked at this for a couple of years, so I can't tell you for sure. But I would try creating the folder.
